import tseslint from 'typescript-eslint';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import jsxA11y from 'eslint-plugin-jsx-a11y';

import { base } from './base.js';
import { djPlugin } from './rules/index.js';

const LAYOUT_THRASH_MESSAGE =
  'Do not transition layout properties - animate transform/opacity/clip-path instead. See docs/03-design-system/motion.md.';

/**
 * A `no-restricted-imports` ban on `**\/server/queries/*` used to live here,
 * meant to stop a Client Component leaf from importing a server-only query
 * module. As written it matched every `.tsx` file with no way to exempt
 * Server Components — which is the documented, correct way to call a query
 * module (`generateMetadata` and every page body in
 * docs/02-architecture/frontend.md and seo.md do exactly this). It made the
 * primary data-fetching pattern of the whole app a lint error.
 *
 * Removed rather than narrowed: the risk it guarded against — a Client
 * Component importing `server-only` code — already fails at build time via
 * the `server-only` package's own runtime guard (every query module and
 * `lib/api-client.ts` starts with `import 'server-only'`), and
 * `dj/no-client-in-route-files` already stops `'use client'` from reaching a
 * page or layout file in the first place. Revisit with a custom rule that
 * actually detects a `'use client'` directive if this needs to be enforced
 * earlier than the build.
 */

/**
 * apps/web and apps/admin.
 *
 * next/core-web-vitals is layered on by each app config via
 * @next/eslint-plugin-next, so this preset stays framework-version agnostic.
 */
export const next = tseslint.config(
  ...base,
  {
    // Generated by `next build` and gitignored. Not ours to lint.
    ignores: ['next-env.d.ts', '.next/**'],
  },
  {
    files: ['**/*.{ts,tsx}'],
    plugins: { react, 'react-hooks': reactHooks, 'jsx-a11y': jsxA11y, dj: djPlugin },
    languageOptions: { parserOptions: { ecmaFeatures: { jsx: true } } },
    settings: { react: { version: 'detect' } },
    rules: {
      ...react.configs.flat.recommended.rules,
      ...react.configs.flat['jsx-runtime'].rules,
      ...reactHooks.configs.recommended.rules,
      ...jsxA11y.flatConfigs.strict.rules,

      // These two encode the two biggest failures of the legacy site.
      'dj/no-client-in-route-files': 'error',
      'dj/no-raw-color-literals': 'error',

      // Animating these properties forces reflow every frame.
      'no-restricted-syntax': [
        'error',
        {
          selector:
            'Property[key.name="transition"] > Literal[value=/\b(width|height|top|left|right|bottom|margin|padding)\b/]',
          message: LAYOUT_THRASH_MESSAGE,
        },
      ],

      'react/no-unescaped-entities': 'off',
      'react/prop-types': 'off',
      'jsx-a11y/no-autofocus': 'error',
      'jsx-a11y/media-has-caption': 'warn',
    },
  },
);

export default next;
