import tseslint from 'typescript-eslint';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import jsxA11y from 'eslint-plugin-jsx-a11y';

import { base } from './base.js';
import { djPlugin } from './rules/index.js';

const LAYOUT_THRASH_MESSAGE =
  'Do not transition layout properties - animate transform/opacity/clip-path instead. See docs/03-design-system/motion.md.';

const SERVER_ONLY_MESSAGE =
  'Server query modules are server-only. Pass data down as props instead of importing them from a client component.';

/**
 * apps/web and apps/admin.
 *
 * next/core-web-vitals is layered on by each app config via
 * @next/eslint-plugin-next, so this preset stays framework-version agnostic.
 */
export const next = tseslint.config(
  ...base,
  {
    // Generated by `next build` and gitignored. Not ours to lint.
    ignores: ['next-env.d.ts', '.next/**'],
  },
  {
    files: ['**/*.{ts,tsx}'],
    plugins: { react, 'react-hooks': reactHooks, 'jsx-a11y': jsxA11y, dj: djPlugin },
    languageOptions: { parserOptions: { ecmaFeatures: { jsx: true } } },
    settings: { react: { version: 'detect' } },
    rules: {
      ...react.configs.flat.recommended.rules,
      ...react.configs.flat['jsx-runtime'].rules,
      ...reactHooks.configs.recommended.rules,
      ...jsxA11y.flatConfigs.strict.rules,

      // These two encode the two biggest failures of the legacy site.
      'dj/no-client-in-route-files': 'error',
      'dj/no-raw-color-literals': 'error',

      // Animating these properties forces reflow every frame.
      'no-restricted-syntax': [
        'error',
        {
          selector:
            'Property[key.name="transition"] > Literal[value=/\b(width|height|top|left|right|bottom|margin|padding)\b/]',
          message: LAYOUT_THRASH_MESSAGE,
        },
      ],

      'react/no-unescaped-entities': 'off',
      'react/prop-types': 'off',
      'jsx-a11y/no-autofocus': 'error',
      'jsx-a11y/media-has-caption': 'warn',
    },
  },
  {
    files: ['**/*.tsx'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['**/server/queries/*', '@dj/api-client/server'],
              message: SERVER_ONLY_MESSAGE,
            },
          ],
        },
      ],
    },
  },
);

export default next;
